name: import_data_IoTree

on:  
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'  # Atualiza no primeiro dia de cada mês https://crontab.guru
  
   
jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with: 
          use-public-rspm: true
      
      - name: Install R Dependencies
        run: |
          Rscript -e "install.packages('remotes')"
          Rscript -e "remotes::install_cran('googlesheets4')"
          Rscript -e "install.packages('lubridate')"
          Rscript -e "install.packages('dplyr')"
          Rscript -e "install.packages('tidyr')"
          Rscript -e "install.packages('stringr')"
          Rscript -e "install.packages('googledrive')"
          
      - name: Run Script
        run: Rscript data_update.R
